/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Remindrop API
 * AI-powered bookmark management API with daily email digests
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteApiBookmarksId200,
  GetApiBookmarks200,
  GetApiBookmarksId200,
  GetApiBookmarksParams,
  PatchApiBookmarksId200,
  PatchApiBookmarksIdBody,
  PostApiBookmarks201,
  PostApiBookmarksBody,
} from './generated.schemas';

import { customInstance } from './mutator/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List user bookmarks
 */
export const getApiBookmarks = (
  params?: GetApiBookmarksParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiBookmarks200>(
    { url: `/api/bookmarks`, method: 'GET', params, signal },
    options
  );
};

export const getGetApiBookmarksQueryKey = (params?: GetApiBookmarksParams) => {
  return [`/api/bookmarks`, ...(params ? [params] : [])] as const;
};

export const getGetApiBookmarksQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBookmarks>>,
  TError = unknown,
>(
  params?: GetApiBookmarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiBookmarksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBookmarks>>> = ({ signal }) =>
    getApiBookmarks(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBookmarks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBookmarksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBookmarks>>>;
export type GetApiBookmarksQueryError = unknown;

export function useGetApiBookmarks<
  TData = Awaited<ReturnType<typeof getApiBookmarks>>,
  TError = unknown,
>(
  params: undefined | GetApiBookmarksParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiBookmarks<
  TData = Awaited<ReturnType<typeof getApiBookmarks>>,
  TError = unknown,
>(
  params?: GetApiBookmarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiBookmarks<
  TData = Awaited<ReturnType<typeof getApiBookmarks>>,
  TError = unknown,
>(
  params?: GetApiBookmarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List user bookmarks
 */

export function useGetApiBookmarks<
  TData = Awaited<ReturnType<typeof getApiBookmarks>>,
  TError = unknown,
>(
  params?: GetApiBookmarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiBookmarksQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new bookmark
 */
export const postApiBookmarks = (
  postApiBookmarksBody: PostApiBookmarksBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostApiBookmarks201>(
    {
      url: `/api/bookmarks`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiBookmarksBody,
      signal,
    },
    options
  );
};

export const getPostApiBookmarksMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiBookmarks>>,
    TError,
    { data: PostApiBookmarksBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiBookmarks>>,
  TError,
  { data: PostApiBookmarksBody },
  TContext
> => {
  const mutationKey = ['postApiBookmarks'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiBookmarks>>,
    { data: PostApiBookmarksBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiBookmarks(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiBookmarksMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiBookmarks>>
>;
export type PostApiBookmarksMutationBody = PostApiBookmarksBody;
export type PostApiBookmarksMutationError = unknown;

/**
 * @summary Create a new bookmark
 */
export const usePostApiBookmarks = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiBookmarks>>,
      TError,
      { data: PostApiBookmarksBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiBookmarks>>,
  TError,
  { data: PostApiBookmarksBody },
  TContext
> => {
  const mutationOptions = getPostApiBookmarksMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get bookmark by ID
 */
export const getApiBookmarksId = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiBookmarksId200>(
    { url: `/api/bookmarks/:id`, method: 'GET', signal },
    options
  );
};

export const getGetApiBookmarksIdQueryKey = () => {
  return [`/api/bookmarks/:id`] as const;
};

export const getGetApiBookmarksIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBookmarksId>>,
  TError = void,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksId>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiBookmarksIdQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBookmarksId>>> = ({ signal }) =>
    getApiBookmarksId(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBookmarksId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBookmarksIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBookmarksId>>
>;
export type GetApiBookmarksIdQueryError = void;

export function useGetApiBookmarksId<
  TData = Awaited<ReturnType<typeof getApiBookmarksId>>,
  TError = void,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksId>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiBookmarksId<
  TData = Awaited<ReturnType<typeof getApiBookmarksId>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksId>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiBookmarksId<
  TData = Awaited<ReturnType<typeof getApiBookmarksId>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get bookmark by ID
 */

export function useGetApiBookmarksId<
  TData = Awaited<ReturnType<typeof getApiBookmarksId>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiBookmarksIdQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update bookmark
 */
export const patchApiBookmarksId = (
  patchApiBookmarksIdBody: PatchApiBookmarksIdBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PatchApiBookmarksId200>(
    {
      url: `/api/bookmarks/:id`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchApiBookmarksIdBody,
    },
    options
  );
};

export const getPatchApiBookmarksIdMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchApiBookmarksId>>,
    TError,
    { data: PatchApiBookmarksIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchApiBookmarksId>>,
  TError,
  { data: PatchApiBookmarksIdBody },
  TContext
> => {
  const mutationKey = ['patchApiBookmarksId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchApiBookmarksId>>,
    { data: PatchApiBookmarksIdBody }
  > = (props) => {
    const { data } = props ?? {};

    return patchApiBookmarksId(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchApiBookmarksIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchApiBookmarksId>>
>;
export type PatchApiBookmarksIdMutationBody = PatchApiBookmarksIdBody;
export type PatchApiBookmarksIdMutationError = void;

/**
 * @summary Update bookmark
 */
export const usePatchApiBookmarksId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchApiBookmarksId>>,
      TError,
      { data: PatchApiBookmarksIdBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchApiBookmarksId>>,
  TError,
  { data: PatchApiBookmarksIdBody },
  TContext
> => {
  const mutationOptions = getPatchApiBookmarksIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete bookmark
 */
export const deleteApiBookmarksId = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<DeleteApiBookmarksId200>(
    { url: `/api/bookmarks/:id`, method: 'DELETE' },
    options
  );
};

export const getDeleteApiBookmarksIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiBookmarksId>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiBookmarksId>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['deleteApiBookmarksId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiBookmarksId>>,
    void
  > = () => {
    return deleteApiBookmarksId(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiBookmarksIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiBookmarksId>>
>;

export type DeleteApiBookmarksIdMutationError = void;

/**
 * @summary Delete bookmark
 */
export const useDeleteApiBookmarksId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiBookmarksId>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteApiBookmarksId>>, TError, void, TContext> => {
  const mutationOptions = getDeleteApiBookmarksIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
