/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Remindrop API
 * AI-powered bookmark management API with daily email digests
 * OpenAPI spec version: 1.0.0
 */
export type GetApiHealth200 = {
  status: string;
  timestamp: string;
  service: string;
  version: string;
};

export type GetApiBookmarksParams = {
  /**
   * Page number (1-indexed)
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page (max 100)
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Field to sort by (createdAt or updatedAt)
   */
  sortBy?: GetApiBookmarksSortBy;
  /**
   * Sort order (asc or desc)
   */
  order?: GetApiBookmarksOrder;
  /**
   * Search query for title or URL (case-insensitive)
   * @maxLength 200
   */
  q?: string;
  /**
   * Filter bookmarks created on or after this date (YYYY-MM-DD)
   * @nullable
   */
  fromDate?: string | null;
  /**
   * Filter bookmarks created on or before this date (YYYY-MM-DD)
   * @nullable
   */
  toDate?: string | null;
};

export type GetApiBookmarksSortBy =
  (typeof GetApiBookmarksSortBy)[keyof typeof GetApiBookmarksSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarksSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type GetApiBookmarksOrder = (typeof GetApiBookmarksOrder)[keyof typeof GetApiBookmarksOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarksOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type GetApiBookmarks200BookmarksItemStatus =
  (typeof GetApiBookmarks200BookmarksItemStatus)[keyof typeof GetApiBookmarks200BookmarksItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarks200BookmarksItemStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type GetApiBookmarks200BookmarksItemCreatedAt = string | string;

export type GetApiBookmarks200BookmarksItemUpdatedAt = string | string;

export type GetApiBookmarks200BookmarksItemTagsItemCreatedAt = string | string;

export type GetApiBookmarks200BookmarksItemTagsItemUpdatedAt = string | string;

export type GetApiBookmarks200BookmarksItemTagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: GetApiBookmarks200BookmarksItemTagsItemCreatedAt;
  updatedAt: GetApiBookmarks200BookmarksItemTagsItemUpdatedAt;
};

export type GetApiBookmarks200BookmarksItem = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: GetApiBookmarks200BookmarksItemStatus;
  createdAt: GetApiBookmarks200BookmarksItemCreatedAt;
  updatedAt: GetApiBookmarks200BookmarksItemUpdatedAt;
  tags?: GetApiBookmarks200BookmarksItemTagsItem[];
};

export type GetApiBookmarks200 = {
  bookmarks: GetApiBookmarks200BookmarksItem[];
  total: number;
  page: number;
  limit: number;
};

export type PostApiBookmarksBody = {
  /** @maxLength 2048 */
  url: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
};

export type PostApiBookmarks201Status =
  (typeof PostApiBookmarks201Status)[keyof typeof PostApiBookmarks201Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBookmarks201Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PostApiBookmarks201CreatedAt = string | string;

export type PostApiBookmarks201UpdatedAt = string | string;

export type PostApiBookmarks201TagsItemCreatedAt = string | string;

export type PostApiBookmarks201TagsItemUpdatedAt = string | string;

export type PostApiBookmarks201TagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: PostApiBookmarks201TagsItemCreatedAt;
  updatedAt: PostApiBookmarks201TagsItemUpdatedAt;
};

export type PostApiBookmarks201 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PostApiBookmarks201Status;
  createdAt: PostApiBookmarks201CreatedAt;
  updatedAt: PostApiBookmarks201UpdatedAt;
  tags?: PostApiBookmarks201TagsItem[];
};

export type GetApiBookmarksId200Status =
  (typeof GetApiBookmarksId200Status)[keyof typeof GetApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type GetApiBookmarksId200CreatedAt = string | string;

export type GetApiBookmarksId200UpdatedAt = string | string;

export type GetApiBookmarksId200TagsItemCreatedAt = string | string;

export type GetApiBookmarksId200TagsItemUpdatedAt = string | string;

export type GetApiBookmarksId200TagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: GetApiBookmarksId200TagsItemCreatedAt;
  updatedAt: GetApiBookmarksId200TagsItemUpdatedAt;
};

export type GetApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: GetApiBookmarksId200Status;
  createdAt: GetApiBookmarksId200CreatedAt;
  updatedAt: GetApiBookmarksId200UpdatedAt;
  tags?: GetApiBookmarksId200TagsItem[];
};

export type PatchApiBookmarksIdBodyStatus =
  (typeof PatchApiBookmarksIdBodyStatus)[keyof typeof PatchApiBookmarksIdBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBookmarksIdBodyStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PatchApiBookmarksIdBody = {
  /** @maxLength 2048 */
  url?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /** @maxLength 50000 */
  content?: string;
  /** @maxLength 2000 */
  summary?: string;
  status?: PatchApiBookmarksIdBodyStatus;
};

export type PatchApiBookmarksId200Status =
  (typeof PatchApiBookmarksId200Status)[keyof typeof PatchApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PatchApiBookmarksId200CreatedAt = string | string;

export type PatchApiBookmarksId200UpdatedAt = string | string;

export type PatchApiBookmarksId200TagsItemCreatedAt = string | string;

export type PatchApiBookmarksId200TagsItemUpdatedAt = string | string;

export type PatchApiBookmarksId200TagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: PatchApiBookmarksId200TagsItemCreatedAt;
  updatedAt: PatchApiBookmarksId200TagsItemUpdatedAt;
};

export type PatchApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PatchApiBookmarksId200Status;
  createdAt: PatchApiBookmarksId200CreatedAt;
  updatedAt: PatchApiBookmarksId200UpdatedAt;
  tags?: PatchApiBookmarksId200TagsItem[];
};

export type DeleteApiBookmarksId200Status =
  (typeof DeleteApiBookmarksId200Status)[keyof typeof DeleteApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type DeleteApiBookmarksId200CreatedAt = string | string;

export type DeleteApiBookmarksId200UpdatedAt = string | string;

export type DeleteApiBookmarksId200TagsItemCreatedAt = string | string;

export type DeleteApiBookmarksId200TagsItemUpdatedAt = string | string;

export type DeleteApiBookmarksId200TagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: DeleteApiBookmarksId200TagsItemCreatedAt;
  updatedAt: DeleteApiBookmarksId200TagsItemUpdatedAt;
};

export type DeleteApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: DeleteApiBookmarksId200Status;
  createdAt: DeleteApiBookmarksId200CreatedAt;
  updatedAt: DeleteApiBookmarksId200UpdatedAt;
  tags?: DeleteApiBookmarksId200TagsItem[];
};

export type PostApiBookmarksIdSummarize200Status =
  (typeof PostApiBookmarksIdSummarize200Status)[keyof typeof PostApiBookmarksIdSummarize200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBookmarksIdSummarize200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PostApiBookmarksIdSummarize200CreatedAt = string | string;

export type PostApiBookmarksIdSummarize200UpdatedAt = string | string;

export type PostApiBookmarksIdSummarize200TagsItemCreatedAt = string | string;

export type PostApiBookmarksIdSummarize200TagsItemUpdatedAt = string | string;

export type PostApiBookmarksIdSummarize200TagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: PostApiBookmarksIdSummarize200TagsItemCreatedAt;
  updatedAt: PostApiBookmarksIdSummarize200TagsItemUpdatedAt;
};

export type PostApiBookmarksIdSummarize200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PostApiBookmarksIdSummarize200Status;
  createdAt: PostApiBookmarksIdSummarize200CreatedAt;
  updatedAt: PostApiBookmarksIdSummarize200UpdatedAt;
  tags?: PostApiBookmarksIdSummarize200TagsItem[];
};

export type PostApiBookmarksIdGenerateTags200BookmarkStatus =
  (typeof PostApiBookmarksIdGenerateTags200BookmarkStatus)[keyof typeof PostApiBookmarksIdGenerateTags200BookmarkStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBookmarksIdGenerateTags200BookmarkStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PostApiBookmarksIdGenerateTags200BookmarkCreatedAt = string | string;

export type PostApiBookmarksIdGenerateTags200BookmarkUpdatedAt = string | string;

export type PostApiBookmarksIdGenerateTags200BookmarkTagsItemCreatedAt = string | string;

export type PostApiBookmarksIdGenerateTags200BookmarkTagsItemUpdatedAt = string | string;

export type PostApiBookmarksIdGenerateTags200BookmarkTagsItem = {
  id: string;
  name: string;
  userId: string;
  createdAt: PostApiBookmarksIdGenerateTags200BookmarkTagsItemCreatedAt;
  updatedAt: PostApiBookmarksIdGenerateTags200BookmarkTagsItemUpdatedAt;
};

export type PostApiBookmarksIdGenerateTags200Bookmark = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PostApiBookmarksIdGenerateTags200BookmarkStatus;
  createdAt: PostApiBookmarksIdGenerateTags200BookmarkCreatedAt;
  updatedAt: PostApiBookmarksIdGenerateTags200BookmarkUpdatedAt;
  tags?: PostApiBookmarksIdGenerateTags200BookmarkTagsItem[];
};

export type PostApiBookmarksIdGenerateTags200 = {
  bookmark: PostApiBookmarksIdGenerateTags200Bookmark;
  /** Generated tags */
  tags: string[];
};
