/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Remindrop API
 * AI-powered bookmark management API with daily email digests
 * OpenAPI spec version: 1.0.0
 */
export type GetApiHealth200 = {
  status: string;
  timestamp: string;
  service: string;
  version: string;
};

export type GetApiBookmarksParams = {
  /**
   * Page number (1-indexed)
   * @minimum 1
   */
  page?: number;
  /**
   * Number of items per page (max 100)
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetApiBookmarks200BookmarksItemStatus =
  (typeof GetApiBookmarks200BookmarksItemStatus)[keyof typeof GetApiBookmarks200BookmarksItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarks200BookmarksItemStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type GetApiBookmarks200BookmarksItemCreatedAt = string | string;

export type GetApiBookmarks200BookmarksItemUpdatedAt = string | string;

export type GetApiBookmarks200BookmarksItem = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: GetApiBookmarks200BookmarksItemStatus;
  createdAt: GetApiBookmarks200BookmarksItemCreatedAt;
  updatedAt: GetApiBookmarks200BookmarksItemUpdatedAt;
};

export type GetApiBookmarks200 = {
  bookmarks: GetApiBookmarks200BookmarksItem[];
  total: number;
  page: number;
  limit: number;
};

export type PostApiBookmarksBody = {
  /** @maxLength 2048 */
  url: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
};

export type PostApiBookmarks201Status =
  (typeof PostApiBookmarks201Status)[keyof typeof PostApiBookmarks201Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBookmarks201Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PostApiBookmarks201CreatedAt = string | string;

export type PostApiBookmarks201UpdatedAt = string | string;

export type PostApiBookmarks201 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PostApiBookmarks201Status;
  createdAt: PostApiBookmarks201CreatedAt;
  updatedAt: PostApiBookmarks201UpdatedAt;
};

export type GetApiBookmarksId200Status =
  (typeof GetApiBookmarksId200Status)[keyof typeof GetApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type GetApiBookmarksId200CreatedAt = string | string;

export type GetApiBookmarksId200UpdatedAt = string | string;

export type GetApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: GetApiBookmarksId200Status;
  createdAt: GetApiBookmarksId200CreatedAt;
  updatedAt: GetApiBookmarksId200UpdatedAt;
};

export type PatchApiBookmarksIdBodyStatus =
  (typeof PatchApiBookmarksIdBodyStatus)[keyof typeof PatchApiBookmarksIdBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBookmarksIdBodyStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PatchApiBookmarksIdBody = {
  /** @maxLength 2048 */
  url?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /** @maxLength 50000 */
  content?: string;
  /** @maxLength 2000 */
  summary?: string;
  status?: PatchApiBookmarksIdBodyStatus;
};

export type PatchApiBookmarksId200Status =
  (typeof PatchApiBookmarksId200Status)[keyof typeof PatchApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type PatchApiBookmarksId200CreatedAt = string | string;

export type PatchApiBookmarksId200UpdatedAt = string | string;

export type PatchApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: PatchApiBookmarksId200Status;
  createdAt: PatchApiBookmarksId200CreatedAt;
  updatedAt: PatchApiBookmarksId200UpdatedAt;
};

export type DeleteApiBookmarksId200Status =
  (typeof DeleteApiBookmarksId200Status)[keyof typeof DeleteApiBookmarksId200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteApiBookmarksId200Status = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type DeleteApiBookmarksId200CreatedAt = string | string;

export type DeleteApiBookmarksId200UpdatedAt = string | string;

export type DeleteApiBookmarksId200 = {
  id: string;
  userId: string;
  url: string;
  /** @minLength 1 */
  title: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  ogImage?: string | null;
  /** @nullable */
  ogDescription?: string | null;
  status: DeleteApiBookmarksId200Status;
  createdAt: DeleteApiBookmarksId200CreatedAt;
  updatedAt: DeleteApiBookmarksId200UpdatedAt;
};
